### ISSUE TITLE
Readme.md 里面modelTest的代码写错了

### ISSUE THREAD

**Issue by chen8840** [snowair/phpunithelper-thinkphp#3]
1.最后一个$output应该改成$user_name
2.self::$app应该改成$app,不然会报错：
`Fatal error: Access to undeclared static property: Home\Model\UserModelTest::$app in E:\chengzhichao\tmp\LMJ\server\Test\Module\UserModuleTest.php on line 10
PHP Fatal error:  Access to undeclared static property: Home\Model\UserModelTest::$app in E:\chengzhichao\tmp\LMJ\server\Test\Module\UserModuleTest.php on line 10`

**Comment by snowair** [comment]
谢谢指正
