### ISSUE TITLE
怎么处理需要请求多个Controller的用例?

### ISSUE THREAD

**Issue by trainyao** [snowair/phpunithelper-thinkphp#4]
setMVC方法只能用一次,如果某些业务需要请求多个Controller里的Action就不能实现.
是否考虑支持动态设置模块和控制器(至少动态设置控制器)?或者已经实现了请教一下如何使用?

**Comment by snowair** [comment]
setMVC 只模拟了控制器，没有限定action，可以支持同一控制器里的所有action。如果控制器没有使用ACTION_NAME常量，都是可以测试的。

**Comment by trainyao** [comment]
同一控制器可以..但是有些情况是要调用控制器A的action之后测试控制器B的action(比如以控制器A action的结果作为前提或者参数)...是否考虑支持这种情况呢?

**Comment by snowair** [comment]
单元测试的重要原则就是测试隔离,降低依赖. 因此才称为unit test.
单元测试方法的输入参数及其预期结果应该是明确的，而不能是动态的，不确定的。所以用a的action输出做b测试的输入是不合适的。

**Comment by trainyao** [comment]
谢谢
