### ISSUE TITLE
composer.json的路径问题和

### ISSUE THREAD

**Issue by ickma** [snowair/phpunithelper-thinkphp#5]
使用了您的测试框架，已经成功！但是有两个地方想咨询一下！  
第一个问题给我在使用`composer.json`创建`autoload.php`文件时，一开始一直提示我`Application`的路径找不到，最后我在`composer.json`中将`Application`和`ThinkPHP`的路径替换成了绝对路径，才成功创建了`autoload.php`文件，我的`composer.json`文件是放在`ThinkPHP/Vendoer/phpunit`路径下的，环境是`windows`环境，是我的路径问题才导致了必须在`composer.json`中使用绝对路径吗？  
第二个问题是我在使用`self::$app = new \Think\PhpunitHelper()`进行实例初始化时，一开始也是一直抛出错误，后来我把`Application`和`ThinkPHP`的绝对路径在初始化时传进去，才成功初始化了APP实例。  
对了，还想了解下，能否在初始化APP实例时传入`cookie`和`userAgent`等变量？

**Comment by ickma** [comment]
您好，我问的三个问题中的最后一个问题**--对了，还想了解下，能否在初始化APP实例时传入cookie和userAgent等变量？--**,这个我自己已经解决， 阅读了一下您的源码，已经找到了方法。

**Comment by snowair** [comment]
composer.json 文件里面的相对目录是相对于其所在的目录的。

**Comment by ickma** [comment]
好的，刚接触composer，我也是这样理解的，多谢！你的测试框架比较好，赞!
